### PR TITLE
added answers for answers.txt

### PR DESCRIPTION
**Pull request by ptoshniasu**

### CODE REVIEW

**Comment by NeelNishant** [comment]
Looks perfect

**Review by darshinshah — APPROVED** [review]
Everything looks perfect. Please submit it.

**Review by NeelNishant — APPROVED** [review]
everything looks fine

**Comment by vnaga2** [comment]
> _No description provided._

Everything looks great.

**Review by kmehta25 — APPROVED** [review]
Looks great

**Pull request merged**
